apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f boca.yaml
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: boca
  name: boca
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: boca
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f boca.yaml
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: boca
    spec:
      containers:
      - env:
        - name: DBHOST
          value: postgres-boca
        - name: DBPASS
          value: boca
        - name: LOG_NAME
          value: boca.host.com
        - name: SERVERNAME
          value: boca.host.com
        image: decomp:boca
        imagePullPolicy: ""
        name: boca
        ports:
        - containerPort: 80
        resources: {}
        securityContext:
          privileged: true
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
