apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f boca.yaml
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: postgres-boca
  name: postgres-boca
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: postgres-boca
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f boca.yaml
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: postgres-boca
    spec:
      containers:
      - env:
        - name: POSTGRES_PASSWORD
          value: boca
        - name: POSTGRES_USER
          value: bocauser
        image: postgres
        imagePullPolicy: ""
        name: postgres-boca
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: db-data
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: db-data
        persistentVolumeClaim:
          claimName: db-data
status: {}
